### PR TITLE
Lots of Bug and Feature Fixes

### PR DESCRIPTION
**Pull request by Elijah629**

### CODE REVIEW

**Comment by nifanfa** [comment]
I’ll merge it when I get home

**Comment by Elijah629** [comment]
It shows that all of the files are deleted, I moved them to /src

**Comment by Elijah629** [comment]
Please reimplement NES, GUI, FConsole, Form; They have been removed

**Comment by Elijah629** [comment]
They have been removed because NES had compile errors in constructor PPU.cs

**Pull request merged**
